# docker-compose.yml
version: "3.9"
services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    env_file:
      - ./api/.env
    depends_on:
      - db
  web:
    build: ./web
    ports:
      - "5173:5173"
    env_file:
      - ./web/.env
    depends_on:
      - api
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: mahjong
      POSTGRES_PASSWORD: mahjong
      POSTGRES_DB: mahjong
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
volumes:
  db_data: {}
